Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vbguest.auto_update = false
  
  config.vm.define "nfss" do |nfss|
    nfss.vm.hostname = "nfss"
    nfss.vm.network "private_network", ip: "192.168.56.10"
    nfss.vm.provision "shell", path: "nfss_script.sh"
  end

  config.vm.define "nfsc" do |nfsc|
    nfsc.vm.hostname = "nfsc"
    nfsc.vm.network "private_network", ip: "192.168.56.11"
    nfsc.vm.provision "shell", path: "nfsc_script.sh"
  end
end

