Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.synced_folder ".", "/home/vagrant/project"
  config.vbguest.auto_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update

    echo "postfix postfix/main_mailer_type string 'Internet Site'" | sudo debconf-set-selections
    echo "postfix postfix/mailname string 'localhost'" | sudo debconf-set-selections
    
    sudo apt-get install -y nginx mailutils postfix cron

    sudo systemctl enable cron
    sudo systemctl start cron

    sudo systemctl enable nginx
    sudo systemctl start nginx

    sudo touch /var/log/nginx/access.log
    sudo touch /var/log/nginx/error.log

    sudo chmod +x /home/vagrant/project/log_analyzer.sh

    echo "0 * * * * root /home/vagrant/project/log_analyzer.sh" | sudo tee /etc/cron.d/log_analyzer
  SHELL
end
